### ISSUE TITLE
Example Sketch for generateBitmap ?

### ISSUE THREAD

**Issue by kd8bxp** [fdufnews/SMART-Response-XE-Low_level#1]
Thank you for your work here, I recently found these devices, and bought some.
But I'm struggling at getting any type of bitmaps to work. generally I get garbage on the screen.
I came across your examples while I was looking for what I was doing, but sadly I'm still having no luck
Do you have an example sketch to display a bitmap? 
Thank you.

**Comment by fdufnews** [comment]
Here is the function I use during the initialization in my BASIC software
`void host_splashscreen(void) {
  const int startHit = 138;
  const int lengthArrow = 84;
  const int startArrow = startHit + 132;
  int pos = startArrow;
  unsigned long pauseArrow = 500ul;
  unsigned long lastTimeArrow = 0;
  unsigned long currenTime = millis();

  SRXELoadBitmapRLE(0, 0, bitmap_logo2_rle);
  SRXEWriteString(startHit, 110, "Hit a key         ", FONT_MEDIUM, 3, 1);
  while (!SRXEGetKey()) {
    currenTime = millis();
    if (currenTime - lastTimeArrow >= pauseArrow) {
      SRXEWriteString(pos, 110, " ", FONT_MEDIUM, 3, 1);
      pos += 12;
      if (pos > startHit + 120 + lengthArrow) pos = startArrow;
      SRXEWriteString(pos, 110, ">", FONT_MEDIUM, 3, 1);
      lastTimeArrow = currenTime;
    }
  };
}`
the bitmap is the one you find in the generateBitmap directory.
I think you can add the function in the helloWorld.ino and call it just after SRXEInit in the setup().
If this work fine, the problem is in the bitmap you are using.

I will update the repo with this function.

**Comment by fdufnews** [comment]
Updated helloWorld in examples which now uses SRXELoadBitmapRLE during setup

**Comment by kd8bxp** [comment]
Worked perfect! Thank you.

I did have to add 
```
void SRXELoadBitmapRLE(int x, int y, const uint8_t *btmp);
```
to 
```
SmartResponseXE.h
```

I think this is a very valuable addition to the original library. Thank you! Saved me from pulling my hair out.

**Comment by fdufnews** [comment]
void SRXELoadBitmapRLE(int x, int y, const uint8_t *btmp); is already in SmartResponseXE.h

I don't know when and where you downloaded the library but SRXELoadBitmapRLE() is included in the library for more than a year.
If you have an older version you'd better download the entire package as I made some improvement from the original one.

**Comment by kd8bxp** [comment]
I was using the original library Larry @bitbank2 https://github.com/bitbank2/SmartResponseXE and just copied your changes.... that was my fault, had I realized you made other changes I would have used yours from the start.
Maybe a pull request back into his repository with all your changes (?)

Either way, I want to thank you again for the help - Your method to create a bitmap and your bitmap addition worked without any issues for me. Thanks again.

**Comment by bitbank2** [comment]
Feel free to do a pull request. I wrote RLE bitmap support into my bb_spi_lcd library.

If you want better compression of 1-bpp images, I would use my TIFF_G4 library. It should run well on the SmartResponseXE if you reduce the buffer sizes and max image width a little.
